### ISSUE TITLE
Ok... I don't necessarily want to be hired..

### ISSUE THREAD

**Issue by darraghpjones** [famly/hire-me#9]
Hi Famly Engineering team.  

I'm a technical user of your software, we use it currently across 4 of our settings.   A long time ago, I spoke to some of your team that mentioned API's might be developed in the future but it doesn't look like that's really happened yet.   We are currently testing out your registration forms but they are a bit of a pain as they take our customers away from our website and our branding in order to do the sign up.  Given the user journey should really stick within the nursery website is there any chance of getting an end point we can send the data to or a component we could embed in our sites to do this.   

Otherwise I love what you're doing!

**Comment by Tuuleh** [comment]
Hey, darraghpjones! 

Could you get in touch with customer success? I think they might be the best equipped to help you. We do have a GraphQL API with self managed access tokens but I think that's a paid feature and I'm not sure what your site is equipped with. I think they might be the best able to help you out. 
I'm not totally sure what APIs might have been discussed and whether you have access to the current GraphQL API, so reaching out to CS might be a good first step :) 
This has generated some interesting conversation about whether iframes could be an option for you but it looks like that would actually not work right now...
We do have some support for creating enquiries in the GraphQL API for our customers, maybe those would do for what you need - but would be good to contact CS and get clarity on the pricing for the self managed tokens.

Best,
Tuuli
